wandb_version: 1

optimizer:
  desc: null
  value: adam
loss:
  desc: null
  value: vae_loss
metric:
  desc: null
  value: accuracy
epoch:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.15.5
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689313499.494165
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 16
      - 23
      4: 3.10.4
      5: 0.15.5
      8:
      - 3
      - 5
